function T = run_parametric_study(cfg)
%RUN_PARAMETRIC_STUDY Runs mesh, Re, scheme, solver, implementation study.

rows = {};

case_id = 0;

for iN = 1:numel(cfg.meshes)
    N = cfg.meshes(iN);

    for iR = 1:numel(cfg.re_list)
        Re = cfg.re_list(iR);

        for is = 1:numel(cfg.schemes)
            scheme = cfg.schemes{is};

            for ip = 1:numel(cfg.pressure_solvers)
                pressure_solver = cfg.pressure_solvers{ip};

                for ii = 1:numel(cfg.implementations)
                    implementation = cfg.implementations{ii};

                    case_id = case_id + 1;
                    case_name = sprintf("case_%03d_N%d_Re%d_%s_%s_%s", ...
                        case_id,N,Re,scheme,pressure_solver,implementation);

                    fprintf("\n[%03d] N=%d Re=%d Scheme=%s Pressure=%s Implementation=%s\n", ...
                        case_id,N,Re,scheme,pressure_solver,implementation);

                    result = solve_lid_cavity(N,Re,scheme,pressure_solver,implementation,cfg);
                    metrics = validate_against_ghia(result,cfg);

                    quality = "not_validated";
                    if result.status == "converged" && metrics.available && metrics.pass
                        quality = "converged_validated";
                    elseif result.status == "converged" && metrics.available && ~metrics.pass
                        quality = "converged_not_validated";
                    elseif result.status == "converged" && ~metrics.available
                        quality = "converged_no_benchmark";
                    elseif result.status ~= "converged" && metrics.available && metrics.pass
                        quality = "validated_but_not_converged";
                    else
                        quality = "needs_improvement";
                    end

                    fprintf("      status=%s quality=%s iter=%d/%d Rc_mass=%.3e Rc_div=%.3e runtime=%.2fs avgPiter=%.1f pSat=%.2f\n", ...
                        result.status,quality,result.iterations,result.localMaxIter,result.final_Rc_mass,result.final_Rc_div, ...
                        result.runtime,result.avg_poisson_iters,result.pressure_saturation_ratio);

                    if metrics.available
                        fprintf("      Ghia L2: u=%.3e(limit %.3e), v=%.3e(limit %.3e), pass=%d\n", ...
                            metrics.u_L2,metrics.u_limit,metrics.v_L2,metrics.v_limit,metrics.pass);
                    end

                    save(fullfile(cfg.data_dir, case_name + ".mat"), "result", "metrics", "quality");

                    if cfg.make_figures && cfg.figure_every_case
                        plot_residuals(result,cfg,case_name);
                        plot_fields(result,cfg,case_name);
                        plot_validation(result,cfg,case_name);
                    end

                    rows(end+1,:) = { ...
                        case_id, ...
                        string(implementation), ...
                        N, ...
                        Re, ...
                        string(scheme), ...
                        string(pressure_solver), ...
                        string(result.status), ...
                        string(quality), ...
                        result.iterations, ...
                        result.localMaxIter, ...
                        result.final_Ru, ...
                        result.final_Rv, ...
                        result.final_Rc_mass, ...
                        result.final_Rc_div, ...
                        result.runtime, ...
                        result.avg_poisson_iters, ...
                        result.avg_poisson_relative_residual, ...
                        result.pressure_saturation_ratio, ...
                        metrics.available, ...
                        metrics.pass, ...
                        metrics.u_L2, ...
                        metrics.v_L2, ...
                        metrics.u_Linf, ...
                        metrics.v_Linf, ...
                        metrics.u_limit, ...
                        metrics.v_limit};
                end
            end
        end
    end
end

T = cell2table(rows, 'VariableNames', { ...
    'CaseID','Implementation','N','Re','Scheme','PressureSolver','Status','Quality', ...
    'Iterations','LocalMaxIter','FinalRu','FinalRv','FinalRcMass','FinalRcDiv','Runtime_s', ...
    'AvgPoissonIterations','AvgPoissonRelResidual','PressureSaturationRatio', ...
    'HasGhia','ValidationPass','Ghia_u_L2','Ghia_v_L2','Ghia_u_Linf','Ghia_v_Linf', ...
    'Ghia_u_L2_Limit','Ghia_v_L2_Limit'});

writetable(T, fullfile(cfg.data_dir, "study_summary.csv"));
save(fullfile(cfg.data_dir, "study_summary.mat"), "T");
end
